### ISSUE TITLE
Remove "N hours ago by PERSON NAME" for TechCrunch articles.

### ISSUE THREAD

**Issue by supersam654** [gt-big-data/QDoc#11]
This isn't part of article content and we don't want it. It's currently only showing up for TC but the fix will ideally prevent it everywhere.

**Comment by mersted** [comment]
I added 'byline' to classList for Techcrunch, which includes "Posted [datetime] by [author]". So not a global fix, but should eliminate the "hours ago" keyword issue with TC articles.

**Comment by mersted** [comment]
Added a few more classes to classList, so crawler won't catch "hours ago" anymore. Also updated the mongodb qdoc collection to update the 'content' and 'keywords' fields.

**Comment by tingofurro** [comment]
There's a new problem of this type: its articles that appear with the keywords: "frog" "species" "horned"
They are BusinessInsider articles.
