### ISSUE TITLE
Make sure the crawler doesn't break if the stamps directory is deleted.

### ISSUE THREAD

**Issue by supersam654** [gt-big-data/QDoc#13]
I haven't confirmed that this breaks the crawler but after glancing at the code, I'm pretty sure it will.

**Comment by tingofurro** [comment]
The stamps are now stored in MongoDB in a collection named "rss_stamps".
Each stamp object in there is of this form:
{u'feed': u'cnn_world', u'stamp': 1443726016, u'_id': ObjectId('560de3c6a6b867b094a9ceb4')}

The folder "stamps/" is not needed anymore
