### ISSUE TITLE
Articles on thehour.com parse very slowly.

### ISSUE THREAD

**Issue by supersam654** [gt-big-data/QDoc#30]
For some reason, all of the articles on http://www.thehour.com parse really slowly. Below is an example article but they're all very slow.

http://www.thehour.com/sports/h-s-football-trinity-catholic-beats-westhill-in-final-game/article_b25db670-8020-11e5-b41e-db5da62110a9.html

**Comment by simon0929** [comment]
I'm working on this.

**Comment by supersam654** [comment]
The articles are still kinda slow but they're better now (~100ms to ~60ms).
